In [3]:
import argparse
import h5py
import numpy as np
import pandas as pd
from sklearn import preprocessing
import os
import time
from pathlib import Path
from urllib.request import urlretrieve
import logging
from li.Baseline import Baseline
from li.LearnedIndex import LearnedIndex
from li.utils import save_as_pickle
from li.model import data_X_to_torch


In [4]:
%reload_ext autoreload
%autoreload 2

In [5]:
np.random.seed(2023)

logging.basicConfig(
    level=logging.INFO,
    format='[%(asctime)s][%(levelname)-5.5s][%(name)-.20s] %(message)s'
)
LOG = logging.getLogger(__name__)


In [6]:
kind='pca32v2'
size='100K'
key='pca32'

In [7]:
data = np.array(h5py.File(os.path.join("data", kind, size, "dataset.h5"), "r")[key])
queries = np.array(h5py.File(os.path.join("data", kind, size, "query.h5"), "r")[key])

In [8]:
kind_search = 'clip768v2'
key_search = 'emb'
data_search = np.array(
    h5py.File(os.path.join("data", kind_search, size, "dataset.h5"), "r")[key_search]
)

In [9]:
queries_search = np.array(
    h5py.File(os.path.join("data", kind_search, size, "query.h5"), "r")[key_search]
)

In [10]:
import torch
from torch import nn
import torch.nn.functional as nnf
import numpy as np
from li.Logger import Logger
from typing import Tuple
import torch.utils.data

torch.manual_seed(2023)
np.random.seed(2023)

class Model(nn.Module):
    def __init__(self, input_dim=768, output_dim=1000, model_type=None):
        super().__init__()
        if model_type == 'MLP':
            self.layers = torch.nn.Sequential(
                torch.nn.Linear(input_dim, 128),
                torch.nn.ReLU(),
                torch.nn.Linear(128, output_dim)
            )
        if model_type == 'MLP-2':
            self.layers = torch.nn.Sequential(
                torch.nn.Linear(input_dim, 64),
                torch.nn.ReLU(),
                torch.nn.Linear(64, output_dim)
            )
        if model_type == 'MLP-3':
            self.layers = torch.nn.Sequential(
                torch.nn.Linear(input_dim, 256),
                torch.nn.ReLU(),
                torch.nn.Linear(256, output_dim)
            )
        if model_type == 'MLP-4':
            self.layers = torch.nn.Sequential(
                torch.nn.Linear(input_dim, 512),
                torch.nn.ReLU(),
                torch.nn.Linear(512, output_dim)
            )
        if model_type == 'MLP-5':
            self.layers = torch.nn.Sequential(
                torch.nn.Linear(input_dim, 256),
                torch.nn.ReLU(),
                torch.nn.Linear(256, 128),
                torch.nn.ReLU(),
                torch.nn.Linear(128, output_dim)
            )
        if model_type == 'MLP-6':
            self.layers = torch.nn.Sequential(
                torch.nn.Linear(input_dim, 32),
                torch.nn.ReLU(),
                torch.nn.Linear(32, output_dim)
            )
        if model_type == 'MLP-7':
            self.layers = torch.nn.Sequential(
                torch.nn.Linear(input_dim, 16),
                torch.nn.ReLU(),
                torch.nn.Linear(16, output_dim)
            )
        if model_type == 'MLP-8':
            self.layers = torch.nn.Sequential(
                torch.nn.Linear(input_dim, 8),
                torch.nn.ReLU(),
                torch.nn.Linear(8, output_dim)
            )
        if model_type == 'MLP-9':
            self.layers = torch.nn.Sequential(
                torch.nn.Linear(input_dim, 8),
                torch.nn.ReLU(),
                torch.nn.Linear(input_dim, 16),
                torch.nn.ReLU(),
                torch.nn.Linear(16, output_dim)
            )
        self.n_output_neurons = output_dim

    def forward(self, x: torch.FloatTensor) -> torch.FloatTensor:
        outputs = self.layers(x)
        return outputs


def data_X_to_torch(data) -> torch.FloatTensor:
    """ Creates torch training data."""
    data_X = torch.from_numpy(np.array(data).astype(np.float32))
    return data_X


def data_to_torch(data, labels) -> Tuple[torch.FloatTensor, torch.LongTensor]:
    """ Creates torch training data and labels."""
    data_X = data_X_to_torch(data)
    data_y = torch.as_tensor(torch.from_numpy(labels), dtype=torch.long)
    return data_X, data_y


def get_device() -> torch.device:
    """ Gets the `device` to be used by torch.
    This arugment is needed to operate with the PyTorch model instance.

    Returns
    ------
    torch.device
        Device
    """
    use_cuda = torch.cuda.is_available()
    device = torch.device('cuda:0' if use_cuda else 'cpu')
    torch.backends.cudnn.benchmark = True
    return device


class NeuralNetwork(Logger):
    """ The neural network class corresponding to every inner node.

    Parameters
    ----------
    input_dim : int
        The input dimension.
    output_dim : int
        The output dimension.
    loss : torch.nn, optional
        The loss function, the default is torch.nn.CrossEntropyLoss.
    lr : float, optional
        The learning rate, the default is 0.001.
    model_type : str, optional
        The model type, the default is 'MLP'.
    class_weight : torch.FloatTensor, optional
        The class weights, the default is None.
    """
    def __init__(
        self,
        input_dim,
        output_dim,
        loss=torch.nn.CrossEntropyLoss,
        lr=0.1,
        model_type='MLP',
        class_weight=None
    ):
        self.device = get_device()
        self.model = Model(input_dim, output_dim, model_type=model_type).to(self.device)
        if not isinstance(class_weight, type(None)):
            self.loss = loss(weight=class_weight.to(self.device))
        else:
            self.loss = loss()
        self.optimizer = torch.optim.Adam(self.model.parameters(), lr=lr)

    def train(
        self,
        data_X: torch.FloatTensor,
        data_y: torch.LongTensor,
        epochs=500,
        logger=None
    ):
        step = epochs // 10
        losses = []
        if logger:
            logger.info(f'Epochs: {epochs}, step: {step}')
        for ep in range(epochs):
            pred_y = self.model(data_X.to(self.device))
            curr_loss = self.loss(pred_y, data_y.to(self.device))
            if ep % step == 0 and ep != 0:
                if logger:
                    logger.info(f'Epoch {ep} | Loss {curr_loss.item()}')
            losses.append(curr_loss.item())

            self.model.zero_grad()
            curr_loss.backward()

            self.optimizer.step()
        return losses

    def train_batch(
        self,
        dataset,
        epochs=5,
        logger=None
    ):
        step = epochs // 10
        step = step if step > 0 else 1
        losses = []
        if logger:
            logger.info(f'Epochs: {epochs}, step: {step}')
        for ep in range(epochs):
            for data_X, data_y in iter(dataset):
                pred_y = self.model(data_X.to(self.device))
                curr_loss = self.loss(pred_y, data_y.to(self.device))

            if ep % step == 0 and ep != 0:
                if logger:
                    logger.info(f'Epoch {ep} | Loss {curr_loss.item():.5f}')
            losses.append(curr_loss.item())

            self.model.zero_grad()
            curr_loss.backward()

            self.optimizer.step()
        return losses

    def predict(self, data_X: torch.FloatTensor):
        """ Collects predictions for multiple data points (used in structure building)."""
        self.model = self.model.to(self.device)
        self.model.eval()

        all_outputs = torch.tensor([], device=self.device)
        with torch.no_grad():
            outputs = self.model(data_X.to(self.device))
            all_outputs = torch.cat((all_outputs, outputs), 0)

        _, y_pred = torch.max(all_outputs, 1)
        return y_pred.cpu().numpy()

    def predict_proba(self, data_X: torch.FloatTensor):
        """ Collects predictions for a single data point (used in query predictions)."""
        self.model = self.model.to(self.device)
        self.model.eval()

        with torch.no_grad():
            outputs = self.model(data_X.to(self.device))

        if outputs.dim() == 1:
            dim = 0
        else:
            dim = 1
        prob = nnf.softmax(outputs, dim=dim)
        probs, classes = prob.topk(prob.shape[1])

        return probs.cpu().numpy(), classes.cpu().numpy()


class LIDataset(torch.utils.data.Dataset):
    def __init__(self, dataset_x, dataset_y):
        self.dataset_x, self.dataset_y = data_to_torch(dataset_x, dataset_y)

    def __len__(self):
        return self.dataset_x.shape[0]

    def __getitem__(self, idx):
        return self.dataset_x[idx-1], self.dataset_y[idx-1]


In [11]:
import numpy as np
from li.Logger import Logger
from li.utils import pairwise_cosine
import time
import torch
import torch.utils.data
import faiss
from tqdm import tqdm
import numpy as np
torch.manual_seed(2023)
np.random.seed(2023)

class LearnedIndex(Logger):

    def __init__(self):
        self.pq = []
        self.model = None

    def search(
        self,
        data_navigation,
        queries_navigation,
        data_search,
        queries_search,
        pred_categories,
        n_buckets=1,
        k=10
    ):
        """ Search for k nearest neighbors for each query in queries.

        Parameters
        ----------
        queries : np.array
            Queries to search for.
        data : np.array
            Data to search in.
        n_buckets : int
            Number of most similar buckets to search in.
        k : int
            Number of nearest neighbors to search for.

        Returns
        -------
        dists : np.array
            Array of shape (queries.shape[0], k) with distances to nearest neighbors for each query.
        anns : np.array
            Array of shape (queries.shape[0], k) with nearest neighbors for each query.
        time : float
            Time it took to search.
        """
        assert self.model is not None, 'Model is not trained, call `build` first.'
        s = time.time()
        _, pred_proba_categories = self.model.predict_proba(
            data_X_to_torch(queries_navigation)
        )
        t_inference = time.time() - s
        anns_final = None
        dists_final = None
        # sorts the predictions of a bucket for each query, ordered by lowest probability
        data_navigation['category'] = pred_categories

        # iterates over the predicted buckets starting from the most similar (index -1)
        t_all_buckets = 0
        t_all_pairwise = 0
        for bucket in range(n_buckets):
            dists, anns, t_all, t_pairwise = self.search_single(
                data_navigation,
                data_search,
                queries_search,
                pred_proba_categories[:, bucket]
            )
            t_all_buckets += t_all
            t_all_pairwise += t_pairwise
            if anns_final is None:
                anns_final = anns
                dists_final = dists
            else:
                # stacks the results from the previous sorted anns and dists
                # *_final arrays now have shape (queries.shape[0], k*2)
                anns_final = np.hstack((anns_final, anns))
                dists_final = np.hstack((dists_final, dists))
                # gets the sorted indices of the stacked dists
                idx_sorted = dists_final.argsort(kind='stable', axis=1)[:, :k]
                # indexes the final arrays with the sorted indices
                # *_final arrays now have shape (queries.shape[0], k)
                idx = np.ogrid[tuple(map(slice, dists_final.shape))]
                idx[1] = idx_sorted
                dists_final = dists_final[tuple(idx)]
                anns_final = anns_final[tuple(idx)]

                assert anns_final.shape == dists_final.shape == (queries_search.shape[0], k)

        return dists_final, anns_final, time.time() - s, t_inference, t_all_buckets, t_all_pairwise

    def search_single(
        self,
        data_navigation,
        data_search,
        queries_search,
        pred_categories,
        k=10
    ):
        """ Search for k nearest neighbors for each query in queries.

        Parameters
        ----------
        queries : np.array
            Queries to search for.
        data : np.array
            Data to search in.
        k : int
            Number of nearest neighbors to search for.

        Returns
        -------
        anns : np.array
            Array of shape (queries.shape[0], k) with nearest neighbors for each query.
        final_dists_k : np.array
            Array of shape (queries.shape[0], k) with distances to nearest neighbors for each query.
        time : float
            Time it took to search.
        """
        s_all = time.time()
        nns = np.zeros((queries_search.shape[0], k), dtype=np.uint32)
        dists = np.zeros((queries_search.shape[0], k), dtype=np.float32)

        if 'category' in data_search.columns:
            data_search = data_search.drop('category', axis=1, errors='ignore')

        t_pairwise = 0
        for cat, g in tqdm(data_navigation.groupby('category')):
            cat_idxs = np.where(pred_categories == cat)[0]
            bucket_obj_indexes = g.index
            if bucket_obj_indexes.shape[0] != 0 and cat_idxs.shape[0] != 0:
                try:
                    s = time.time()
                    seq_search_dists = pairwise_cosine(
                        queries_search[cat_idxs],
                        data_search.loc[bucket_obj_indexes]
                    )
                    t_pairwise += time.time() - s
                    ann_relative = seq_search_dists.argsort()[
                        :, :k if k < seq_search_dists.shape[1] else seq_search_dists.shape[1]
                    ]
                    nns[cat_idxs] = np.array(bucket_obj_indexes)[ann_relative]
                    dists[cat_idxs] = np.take_along_axis(seq_search_dists, ann_relative, axis=1)
                except ValueError as e:
                    print(e)
                    print('cat_idxs', cat_idxs.shape)
                    print('bucket_obj_indexes', bucket_obj_indexes.shape)
                    print('seq_search_dists', seq_search_dists.shape)
                    print('ann_relative', ann_relative.shape)

        t_all = time.time() - s_all
        return dists, nns, t_all, t_pairwise

    def build(self, data, n_categories=100, epochs=100, lr=0.1, model_type='MLP'):
        """ Build the index.

        Parameters
        ----------
        data : np.array
            Data to build the index on.

        Returns
        -------
        time : float
            Time it took to build the index.
        """
        s = time.time()
        # ---- cluster the data into categories ---- #
        _, labels = self.cluster(data, n_categories)

        # ---- train a neural network ---- #
        dataset = LIDataset(data, labels)
        train_loader = torch.utils.data.DataLoader(
            dataset,
            batch_size=256,
            sampler=torch.utils.data.SubsetRandomSampler(
                data.index.values.tolist()
            )
        )
        nn = NeuralNetwork(
            input_dim=data.shape[1],
            output_dim=n_categories,
            lr=lr,
            model_type=model_type
        )
        nn.train_batch(train_loader, epochs=epochs, logger=self.logger)
        # ---- collect predictions ---- #
        self.model = nn
        return nn.predict(data_X_to_torch(data)), time.time() - s

    def cluster(
        self,
        data,
        n_clusters,
        n_redo=10,
        spherical=True,
        int_centroids=True,

    ):
        if data.shape[0] < 2:
            return None, np.zeros_like(data.shape[0])

        if data.shape[0] < n_clusters:
            n_clusters = data.shape[0] // 5
            if n_clusters < 2:
                n_clusters = 2

        kmeans = faiss.Kmeans(
            d=np.array(data).shape[1],
            k=n_clusters,
            verbose=True,
            #nredo=n_redo,
            #spherical=spherical,
            #int_centroids=int_centroids,
            #update_index=False,
            seed=2023
        )
        X = np.array(data).astype(np.float32)
        kmeans.train(X)

        return kmeans, kmeans.index.search(X, 1)[1].T[0]


[2023-07-14 13:48:44,472][INFO ][faiss.loader] Loading faiss with AVX2 support.
[2023-07-14 13:48:44,475][INFO ][faiss.loader] Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'",)
[2023-07-14 13:48:44,477][INFO ][faiss.loader] Loading faiss.
[2023-07-14 13:48:44,666][INFO ][faiss.loader] Successfully loaded faiss.


In [12]:
data = pd.DataFrame(data)
data.index += 1

data_search = pd.DataFrame(data_search)
data_search.index += 1

In [13]:
li = LearnedIndex()
pred_categories, build_t = li.build(
    data,
    n_categories=2000,
    epochs=20,
    lr=0.1
)

[2023-07-14 13:49:02,336][INFO ][__main__.LearnedInde] Epochs: 20, step: 2
[2023-07-14 13:49:12,698][INFO ][__main__.LearnedInde] Epoch 2 | Loss 7.68513
[2023-07-14 13:49:19,558][INFO ][__main__.LearnedInde] Epoch 4 | Loss 7.65066
[2023-07-14 13:49:26,454][INFO ][__main__.LearnedInde] Epoch 6 | Loss 7.62184
[2023-07-14 13:49:33,290][INFO ][__main__.LearnedInde] Epoch 8 | Loss 7.54541
[2023-07-14 13:49:40,159][INFO ][__main__.LearnedInde] Epoch 10 | Loss 7.51368
[2023-07-14 13:49:47,065][INFO ][__main__.LearnedInde] Epoch 12 | Loss 7.52358
[2023-07-14 13:49:54,213][INFO ][__main__.LearnedInde] Epoch 14 | Loss 7.57553
[2023-07-14 13:50:01,142][INFO ][__main__.LearnedInde] Epoch 16 | Loss 7.44283
[2023-07-14 13:50:07,976][INFO ][__main__.LearnedInde] Epoch 18 | Loss 7.35205


In [14]:
data['category'] = pred_categories

In [15]:
data.category.value_counts()

791     17037
1878    13664
237      9391
1913     8733
1830     6419
        ...  
182         1
1452        1
1617        1
285         1
810         1
Name: category, Length: 97, dtype: int64

In [16]:
k=10

In [17]:
nns = np.zeros((queries_search.shape[0], k), dtype=np.uint32)
dists = np.zeros((queries_search.shape[0], k), dtype=np.float32)

In [18]:
_, pred_proba_categories = li.model.predict_proba(
    data_X_to_torch(queries)
)

In [20]:
bucket = 0

In [18]:
pred_proba_categories

array([[ 791, 1878, 1144, ...,  542, 1020, 1010],
       [ 791, 1913,  708, ..., 1535,  434, 1547],
       [ 276,  911, 1864, ...,  823, 1636,  190],
       ...,
       [1665,  349, 1418, ..., 1563,  542, 1229],
       [ 791, 1913, 1428, ..., 1020, 1955, 1547],
       [1144,  791, 1878, ..., 1229,  542, 1547]])

In [21]:
for cat, g in tqdm(data.groupby('category')):
    cat_idxs = np.where(pred_proba_categories[:, bucket] == cat)[0]
    bucket_obj_indexes = g.index
    print(queries_search[cat_idxs].shape)
    print(data_search.loc[bucket_obj_indexes].shape)
    break
    seq_search_dists = pairwise_cosine(
        queries_search[cat_idxs],
        data_search.loc[bucket_obj_indexes]
    )
    break

  0%|          | 0/97 [00:00<?, ?it/s]

(322, 768)
(3095, 768)


In [20]:
dists.max(axis=1)

array([0., 0., 0., ..., 0., 0., 0.], dtype=float32)

In [21]:
dists

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [22]:
max(dists)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [22]:
for cat, g in tqdm(data.groupby('category')):
    cat_idxs = np.where(pred_proba_categories[:, bucket] == cat)[0]
    bucket_obj_indexes = g.index
    if bucket_obj_indexes.shape[0] != 0 and cat_idxs.shape[0] != 0:
        #print(cat, cat_idxs, cat_idxs.shape)
        #break
        seq_search_dists = pairwise_cosine(
            queries_search[cat_idxs],
            data_search.loc[bucket_obj_indexes]
        )
        #print(seq_search_dists.shape)
        ann_relative = seq_search_dists.argsort()[
            :, :k if k < seq_search_dists.shape[1] else seq_search_dists.shape[1]
        ]
        #print('ann_relative: ', ann_relative.shape)
        #print('np.array(bucket_obj_indexes): ', np.array(bucket_obj_indexes), np.array(bucket_obj_indexes).shape)
        #print('ann_relative: ', ann_relative, ann_relative.shape)
        pad_needed = (k - np.array(bucket_obj_indexes).shape[0]) // 2 + 1
        #print('pad_needed: ', pad_needed)
        #print('np.array(bucket_obj_indexes) padded: ', np.pad(np.array(bucket_obj_indexes), pad_needed, 'edge')[:k], np.pad(np.array(bucket_obj_indexes), pad_needed,'edge').shape)
        if bucket_obj_indexes.shape[0] < k:
            #print('here')
            pad_needed = (k - bucket_obj_indexes.shape[0]) // 2 + 1
            bucket_obj_indexes = np.pad(np.array(bucket_obj_indexes), pad_needed, 'edge')[:k]
            ann_relative = np.pad(ann_relative[0], pad_needed, 'edge')[:k].reshape(1, -1)
            seq_search_dists = np.pad(seq_search_dists[0], pad_needed, 'edge')[:k].reshape(1, -1)
            #print('seq_search_dists: ', seq_search_dists)
            u, i = np.unique(seq_search_dists, return_index=True)
            duplicates_i = np.setdiff1d(np.arange(k), i)
            # assign a large number such that the duplicated value gets replaced
            seq_search_dists[0][duplicates_i] = 10_000
            #print('seq_search_dists: ', seq_search_dists)
            #print('bucket_obj_indexes: ', bucket_obj_indexes.shape)
            #print('ann_relative: ', ann_relative, ann_relative.shape)
            #print('seq_search_dists ', seq_search_dists, seq_search_dists.shape)

        nns[cat_idxs] = np.array(bucket_obj_indexes)[ann_relative]
        #print('nns[cat_idxs]: ', nns[cat_idxs].shape)
        dists[cat_idxs] = np.take_along_axis(seq_search_dists, ann_relative, axis=1)

100%|██████████| 97/97 [00:09<00:00, 10.54it/s]


In [23]:
cat_idxs.shape

(0,)

In [35]:
nns

array([[79172, 74173, 71849, ..., 80243, 21472, 70410],
       [14347, 82848, 79302, ..., 53783, 84845, 78536],
       [29237,  4207, 88213, ..., 12212, 35067, 44556],
       ...,
       [47854,  4982, 75313, ..., 33171, 50438, 78418],
       [26945, 85710, 39351, ..., 97137, 77608, 83898],
       [24525,  3924, 54312, ..., 17209,  8939, 67996]], dtype=uint32)

In [36]:
bucket_obj_indexes

Int64Index([77009, 80169], dtype='int64')

In [37]:
ann_relative

array([[ 73,  72,  37,  48,  99,  77, 126, 105, 100,  51],
       [  6,  63,  39,   5, 106, 103,   4,  29,  49, 107],
       [115,  97,  64,  50, 111,  62, 100,  92,  22, 122],
       [  0, 104,  35,  11,  46,   9, 134,  81,  60,  84],
       [ 16,  78,  91,  81,  56, 124, 119, 130, 134,   2],
       [ 29,  71,  54, 106,  52, 107, 109,  66, 101, 103],
       [  0,  67,  46,  11,   9,  59, 118,  10,  60,  45],
       [ 20,  57,  46,  11,  30,   2,   0,  10, 118, 123],
       [ 76,  75,   2,  40, 134,  11, 105,   0, 118,  30],
       [ 38,  74, 121,  55, 128,  76,  17, 130,  43,  90],
       [ 40,  76,  88,  81, 128, 121,  55,  60, 130,  59],
       [ 66,   7,   8,  55,  42,  94,  80, 131,  56, 125],
       [ 49, 103,  94, 116,  29, 105,  24,  54,  71,   0],
       [106,  54,   5,  52, 107,  94,  29,  71, 125, 131],
       [ 45,  46,   2,   0,  20, 105,  11,  12,  75,  10],
       [ 57,  60, 113, 118, 134,  11, 102,  46,  30, 121],
       [ 91, 124,  56,  78, 119,  16,  81, 104,   2,   8

In [38]:
cat_idxs

array([], dtype=int64)

In [39]:
np.array(bucket_obj_indexes)[ann_relative]

IndexError: index 73 is out of bounds for axis 0 with size 2

In [23]:
from sklearn.metrics.pairwise import cosine_similarity
for cat, g in tqdm(data.groupby('category')):
    bucket = 1
    print(cat, g.shape)
    cat_idxs = np.where(pred_proba_categories[:, bucket] == cat)[0]
    bucket_obj_indexes = g.index
    print(queries_search[cat_idxs].shape)
    x = queries_search[cat_idxs]
    y = data_search.loc[bucket_obj_indexes]
    pure_arr = 1-cosine_similarity(x, y)
    break

  0%|          | 0/97 [00:00<?, ?it/s]

37 (3095, 33)
(176, 768)


In [24]:
def pairwise_cosine_threshold(x, y, threshold, cat_idxs, k=10):
    s = time.time()
    result = 1-cosine_similarity(x, y)
    t_pure_seq_search = time.time() - s
    # create an array of consisten shapes
    #print(result.shape)
    #print(threshold.shape, threshold[cat_idxs].shape)
    thresh_consistent = np.repeat(threshold[cat_idxs, np.newaxis], result.shape[1], 1)
    relevant_dists = np.where(result < thresh_consistent)
    # filter the relevant object ids
    try:
        relevant_object_ids = np.unique(relevant_dists[1])
        max_idx = relevant_object_ids.shape[0]
        if max_idx == 0:
            return None, t_pure_seq_search
    except ValueError:
        # There is no distance below the threshold, we can return
        return None, t_pure_seq_search
    max_idx = max_idx if max_idx > k else k
    # output array filled with some large value
    output_arr = np.full(shape=(result.shape[0], max_idx), fill_value=10_000, dtype=np.float)
    #index_df = pd.DataFrame(relevant_dists[0])
    #index_df = pd.DataFrame(relevant_dists[0], relevant_dists[1]).reset_index()
    # create indexes to store the relevant distances
    #index_df['mapping'] = index_df.groupby('index').ngroup()
    mapping = dict(zip(relevant_object_ids, np.arange(relevant_object_ids.shape[0])))
    # tried also with np.vectorize, wasn't faster
    output_arr_2nd_dim = np.array([mapping[x] for x in relevant_dists[1]])
    to_be_added = result[relevant_dists[0], relevant_dists[1]]
    # populate the output array
    output_arr[relevant_dists[0], output_arr_2nd_dim] = to_be_added
    return output_arr, relevant_object_ids, t_pure_seq_search


In [26]:
threshold_dist = dists.max(axis=1)

In [27]:
seq_search_dists = pairwise_cosine_threshold(
    queries_search[cat_idxs],
    data_search.loc[bucket_obj_indexes],
    threshold_dist,
    cat_idxs,
    k
)

In [ ]:
seq_search_dists

In [28]:
seq_search_dists[0].shape

(176, 1242)

In [ ]:
bucket_obj_indexes_old = bucket_obj_indexes

In [74]:
bucket_obj_indexes = bucket_obj_indexes[seq_search_dists[1]]

In [50]:
bucket_obj_indexes_old

Int64Index([   63,   111,   124,   134,   266,   317,   341,   357,   394,
              424,
            ...
            99610, 99656, 99687, 99689, 99699, 99700, 99701, 99716, 99722,
            99945],
           dtype='int64', length=3095)

In [51]:
bucket_obj_indexes

Int64Index([  341,   538,   569,   895,  1229,  1526,  1575,  1747,  1786,
             1864,
            ...
            98324, 98330, 98604, 98795, 99156, 99171, 99407, 99580, 99687,
            99700],
           dtype='int64', length=883)

In [75]:
seq_search_dists = seq_search_dists[0]

In [76]:
seq_search_dists.shape

(176, 883)

In [77]:
ann_relative = seq_search_dists.argsort(kind='quicksort')[
    :, :k if k < seq_search_dists.shape[1] else seq_search_dists.shape[1]
]

In [78]:
ann_relative

array([[662, 417, 225, ..., 370, 824, 585],
       [ 20, 214, 289, ..., 516, 228, 119],
       [216,  48, 544, ..., 867, 256, 585],
       ...,
       [667, 222, 208, ..., 156, 783,   0],
       [719, 288, 138, ..., 716, 372, 290],
       [731, 249, 214, ..., 642, 514,   0]])

In [56]:
nns

array([[79172, 74173, 71849, ..., 80243, 21472, 70410],
       [14347, 82848, 79302, ..., 53783, 84845, 78536],
       [29237,  4207, 88213, ..., 12212, 35067, 44556],
       ...,
       [47854,  4982, 75313, ..., 33171, 50438, 78418],
       [26945, 85710, 39351, ..., 97137, 77608, 83898],
       [24525,  3924, 54312, ..., 17209,  8939, 67996]], dtype=uint32)

In [ ]:
np.array(bucket_obj_indexes)[ann_relative]

In [57]:
15735 in bucket_obj_indexes_old

False

In [58]:
ann_relative_old = pure_arr.argsort(kind='quicksort')[
    :, :k if k < pure_arr.shape[1] else pure_arr.shape[1]
]

In [59]:
np.array(bucket_obj_indexes_old)[ann_relative_old]

array([[74129, 44945, 25198, ..., 39394, 93083, 98067],
       [ 3423, 23584, 31903, ..., 56226, 25536, 13676],
       [23673,  6535, 58984, ..., 97746, 28616, 63270],
       ...,
       [74487, 24829, 23029, ..., 17039, 88277, 74393],
       [80945, 31819, 15405, ..., 80576, 39503, 32064],
       [82118, 28022, 23584, ..., 71210, 56088, 56675]])

In [60]:
ann_relative_old

array([[2341, 1427,  803, ..., 1256, 2899, 3041],
       [  86,  749, 1033, ..., 1782,  820,  422],
       [ 755,  190, 1872, ..., 3030,  912, 1980],
       ...,
       [2351,  786,  731, ...,  528, 2745, 2349],
       [2535, 1031,  472, ..., 2526, 1265, 1036],
       [2569,  893,  749, ..., 2253, 1777, 1796]])

In [61]:
ann_relative

array([[  7,   4,   1, ...,   3,   8, 592],
       [  0,   4,   6, ...,   9,   5,   3],
       [  1,   0,   4, ...,   8,   3, 592],
       ...,
       [  7,   3,   2, ...,   1,   8, 592],
       [  9,   2,   0, ...,   8,   5,   3],
       [  7,   2,   1, ...,   6,   4, 592]])

In [63]:
bucket_obj_indexes_old[2341]

74129

In [64]:
bucket_obj_indexes[7]

1747

In [65]:
74129 in bucket_obj_indexes

True

In [66]:
bucket_obj_indexes

Int64Index([  341,   538,   569,   895,  1229,  1526,  1575,  1747,  1786,
             1864,
            ...
            98324, 98330, 98604, 98795, 99156, 99171, 99407, 99580, 99687,
            99700],
           dtype='int64', length=883)

In [ ]:
pure_arr

##### Objective: beat the time of:

In [25]:
bucket_obj_indexes

Int64Index([   63,   111,   124,   134,   266,   317,   341,   357,   394,
              424,
            ...
            99610, 99656, 99687, 99689, 99699, 99700, 99701, 99716, 99722,
            99945],
           dtype='int64', length=3095)

In [31]:
bucket_obj_indexes[np.unique(relevant_dists[1])]

Int64Index([  341,   538,   569,   895,  1229,  1526,  1575,  1747,  1786,
             1864,
            ...
            98324, 98330, 98604, 98795, 99156, 99171, 99407, 99580, 99687,
            99700],
           dtype='int64', length=883)

In [32]:
np.array(bucket_obj_indexes)[np.unique(relevant_dists[1])]

array([  341,   538,   569,   895,  1229,  1526,  1575,  1747,  1786,
        1864,  2047,  2339,  2428,  2516,  2650,  2863,  2865,  2992,
        3087,  3296,  3423,  3430,  3445,  3499,  3510,  3587,  3643,
        3668,  3672,  3897,  4058,  4269,  4334,  4616,  4669,  4824,
        5011,  5100,  5181,  5461,  5486,  5511,  5549,  5604,  5899,
        6000,  6150,  6166,  6535,  6723,  6738,  6768,  6813,  6871,
        7159,  7372,  7494,  7635,  7690,  7717,  7732,  7734,  7932,
        8004,  8166,  8311,  8668,  8690,  8863,  8919,  8962,  8979,
        9176,  9185,  9432,  9523,  9624,  9942,  9974, 10154, 10185,
       10210, 10378, 10411, 10566, 10573, 10899, 11145, 11327, 11509,
       11542, 11660, 11702, 11800, 11849, 11899, 11996, 12198, 12215,
       12220, 12248, 12353, 12473, 12514, 12526, 12551, 12574, 12576,
       13152, 13175, 13242, 13337, 13339, 13361, 13438, 13453, 13529,
       13625, 13669, 13676, 13703, 13862, 13866, 14044, 14089, 14118,
       14253, 14281,

In [35]:
%%time
ann_relative = pure_arr.argsort(kind='quicksort')[
    :, :10
]

CPU times: user 33.8 ms, sys: 30 µs, total: 33.8 ms
Wall time: 33.8 ms


In [36]:
%%time
max_dists = dists.max(axis=1)[cat_idxs]

CPU times: user 616 µs, sys: 11 µs, total: 627 µs
Wall time: 632 µs


In [37]:
max_dists.shape

(176,)

In [128]:
pure_arr.shape

(176, 3095)

In [27]:
%time thresh_consistent = np.repeat(dists.max(axis=1)[cat_idxs, np.newaxis], 3095, 1)

CPU times: user 2.66 ms, sys: 0 ns, total: 2.66 ms
Wall time: 2.67 ms


In [130]:
thresh_consistent

array([[0.41322672, 0.41322672, 0.41322672, ..., 0.41322672, 0.41322672,
        0.41322672],
       [0.50706047, 0.50706047, 0.50706047, ..., 0.50706047, 0.50706047,
        0.50706047],
       [0.56162024, 0.56162024, 0.56162024, ..., 0.56162024, 0.56162024,
        0.56162024],
       ...,
       [0.40540254, 0.40540254, 0.40540254, ..., 0.40540254, 0.40540254,
        0.40540254],
       [0.2505514 , 0.2505514 , 0.2505514 , ..., 0.2505514 , 0.2505514 ,
        0.2505514 ],
       [0.42306498, 0.42306498, 0.42306498, ..., 0.42306498, 0.42306498,
        0.42306498]], dtype=float32)

In [30]:
relevant_dists = np.where(pure_arr < thresh_consistent)

In [135]:
np.unique(relevant_dists[1]).shape

(883,)

In [136]:
max_idx = np.unique(relevant_dists[1]).shape[0]

In [137]:
%time output_arr = np.full(shape=(result.shape[0], max_idx), fill_value=10_000, dtype=np.float)


CPU times: user 132 µs, sys: 6 µs, total: 138 µs
Wall time: 143 µs


In [141]:
mapping = np.sort(np.unique(relevant_dists[1]))

In [144]:
to_be_added = result[relevant_dists[0], relevant_dists[1]]
to_be_added.shape

(1672,)

In [157]:
to_be_added

array([0.38112549, 0.37429338, 0.38054658, ..., 0.42050421, 0.2800742 ,
       0.37362603])

In [156]:
output_arr

array([[10000., 10000., 10000., ..., 10000., 10000., 10000.],
       [10000., 10000., 10000., ..., 10000., 10000., 10000.],
       [10000., 10000., 10000., ..., 10000., 10000., 10000.],
       ...,
       [10000., 10000., 10000., ..., 10000., 10000., 10000.],
       [10000., 10000., 10000., ..., 10000., 10000., 10000.],
       [10000., 10000., 10000., ..., 10000., 10000., 10000.]])

In [147]:
output_arr.shape

(176, 883)

In [155]:
np.arange(output_arr.shape[0]).shape

(176,)

In [165]:
%%time
index_df = pd.DataFrame(relevant_dists[0], relevant_dists[1]).reset_index()

CPU times: user 1.14 ms, sys: 58 µs, total: 1.2 ms
Wall time: 1.21 ms


In [175]:
index_df['index'].values

array([ 433,  803,  932, ..., 2253, 2569, 2926])

In [177]:
np.where(index_df['index'].values == mapping)#[0][0]

/mnt/storage-brno11-elixir/home/tslaninakova/dynamic-lmi/dynamic-lmi-env/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


(array([], dtype=int64),)

In [166]:
%%time
index_df['mapping'] = index_df.index.apply(lambda x: x)

index    0
0       433    0
1       803    0
2       932    0
3      1256    0
4      1427    0
...     ...  ...
1667   1777  175
1668   1854  175
1669   2253  175
1670   2569  175
1671   2926  175

[1672 rows x 2 columns]

In [183]:
%time index_df['mapping'] = index_df.groupby('index').ngroup()

CPU times: user 2.36 ms, sys: 131 µs, total: 2.49 ms
Wall time: 2.5 ms


In [184]:
index_df

index    0  mapping
0       433    0      123
1       803    0      225
2       932    0      261
3      1256    0      370
4      1427    0      417
...     ...  ...      ...
1667   1777  175      514
1668   1854  175      542
1669   2253  175      642
1670   2569  175      731
1671   2926  175      835

[1672 rows x 3 columns]

In [187]:
index_df[0].values, index_df['mapping'].values

(array([  0,   0,   0, ..., 175, 175, 175]),
 array([123, 225, 261, ..., 642, 731, 835]))

In [185]:
output_arr[index_df[0].values, index_df['mapping'].values] = to_be_added

In [186]:
output_arr

array([[10000., 10000., 10000., ..., 10000., 10000., 10000.],
       [10000., 10000., 10000., ..., 10000., 10000., 10000.],
       [10000., 10000., 10000., ..., 10000., 10000., 10000.],
       ...,
       [10000., 10000., 10000., ..., 10000., 10000., 10000.],
       [10000., 10000., 10000., ..., 10000., 10000., 10000.],
       [10000., 10000., 10000., ..., 10000., 10000., 10000.]])

In [189]:
%%time
ann_relative_2 = output_arr.argsort(kind='quicksort')[
    :, :10
]
ann_relative_2

CPU times: user 3.58 ms, sys: 0 ns, total: 3.58 ms
Wall time: 3.6 ms


array([[662, 417, 225, ..., 370, 824, 585],
       [ 20, 214, 289, ..., 516, 228, 119],
       [216,  48, 544, ..., 867, 256, 585],
       ...,
       [667, 222, 208, ..., 156, 783,   0],
       [719, 288, 138, ..., 716, 372, 290],
       [731, 249, 214, ..., 642, 514,   0]])

In [191]:
mapping_d = dict(zip(index_df['mapping'], index_df['index']))

In [ ]:
mapping_ar = np.zeros(k.max()+1,dtype=v.dtype)

In [193]:
mapping_d[ann_relative_2]

TypeError: unhashable type: 'numpy.ndarray'

In [199]:
idx = np.nonzero(mapping_d.keys() == ann_relative_2[:,None])[1]

In [202]:
out = np.asarray(mapping_d.values())

In [203]:
out.shape

()

In [200]:
idx.shape

(0,)

In [195]:
%time idx = np.searchsorted(mapping_d.keys(),ann_relative_2,sorter = sort_idx)

ValueError: object of too small depth for desired array

In [188]:
output_arr.shape

(176, 883)

In [40]:
dists.max(axis=1).shape

(10000,)

In [41]:
cat_idxs.shape

(176,)

In [42]:
pure_arr.shape

(176, 3095)

In [127]:
res = thresh_consistent

In [48]:
%%time
target_dists = np.where(pure_arr < res)

CPU times: user 3.12 ms, sys: 0 ns, total: 3.12 ms
Wall time: 15.7 ms


In [65]:
target_dists

(array([  0,   0,   0, ..., 175, 175, 175]),
 array([ 433,  803,  932, ..., 2253, 2569, 2926]))

In [49]:
%%time
max_idx = np.unique(target_dists[0], return_counts=True)[1].max()
max_idx

CPU times: user 332 µs, sys: 7 µs, total: 339 µs
Wall time: 343 µs


10

In [36]:
target_dists

(array([  2,   2,   2, ..., 174, 174, 175]),
 array([ 190,  755, 1872, ..., 2538, 2995, 2569]))

In [50]:
%time sample_arr = np.full(shape=(pure_arr.shape[0], max_idx), fill_value=10_000, dtype=np.float)

CPU times: user 160 µs, sys: 3 µs, total: 163 µs
Wall time: 167 µs


In [57]:
%time sample_arr_mapping = np.full(shape=(pure_arr.shape[0], max_idx), fill_value=-1, dtype=np.float)

CPU times: user 269 µs, sys: 7 µs, total: 276 µs
Wall time: 283 µs


In [51]:
sample_arr.shape

(176, 10)

In [52]:
%time to_be_added = pure_arr[target_dists[0], target_dists[1]]

CPU times: user 213 µs, sys: 4 µs, total: 217 µs
Wall time: 222 µs


In [53]:
%time to_be_added = pure_arr[target_dists[0], target_dists[1]]

CPU times: user 181 µs, sys: 3 µs, total: 184 µs
Wall time: 189 µs


In [62]:
to_be_added.shape

(1672,)

In [60]:
target_dists[1].shape

(2379,)

In [54]:
%time index_df = pd.DataFrame(target_dists[0])

CPU times: user 209 µs, sys: 4 µs, total: 213 µs
Wall time: 218 µs


In [57]:
%time index_df['new_arr_idx'] = index_df.groupby(0).cumcount()

CPU times: user 2.73 ms, sys: 0 ns, total: 2.73 ms
Wall time: 2.74 ms


In [69]:
index_df['value'] = to_be_added
index_df['old_idx'] = target_dists[1]

In [58]:
%time sample_arr[index_df.values[:, 0], index_df.values[:, 1]] = to_be_added

CPU times: user 671 µs, sys: 14 µs, total: 685 µs
Wall time: 690 µs


In [59]:
sample_arr

array([[3.81125490e-01, 3.74293381e-01, 3.80546576e-01, ...,
        3.54262565e-01, 4.12724845e-01, 1.00000000e+04],
       [4.73876682e-01, 4.96774658e-01, 5.00576416e-01, ...,
        5.04241098e-01, 4.96301041e-01, 5.04272814e-01],
       [4.99491491e-01, 4.91069871e-01, 5.22439371e-01, ...,
        5.04918345e-01, 5.35762477e-01, 1.00000000e+04],
       ...,
       [3.98160039e-01, 4.02001756e-01, 3.93275729e-01, ...,
        3.76518875e-01, 4.03970985e-01, 1.00000000e+04],
       [1.43215593e-01, 2.17929883e-01, 1.38970976e-01, ...,
        2.16701151e-01, 2.43290125e-01, 8.61833045e-02],
       [3.97648318e-01, 3.49436687e-01, 3.45120891e-01, ...,
        2.80074201e-01, 3.73626027e-01, 1.00000000e+04]])

In [66]:
%%time
ann_relative = pure_arr.argsort(kind='quicksort')[
    :, :10
]
ann_relative

CPU times: user 37.9 ms, sys: 0 ns, total: 37.9 ms
Wall time: 37.9 ms


array([[2341, 1427,  803, ..., 1256, 2899, 3041],
       [  86,  749, 1033, ..., 1782,  820,  422],
       [ 755,  190, 1872, ..., 3030,  912, 1980],
       ...,
       [2351,  786,  731, ...,  528, 2745, 2349],
       [2535, 1031,  472, ..., 2526, 1265, 1036],
       [2569,  893,  749, ..., 2253, 1777, 1796]])

In [83]:
%%time
dists_relative = np.sort(sample_arr, kind='quicksort')[
    :, :10
]
dists_relative

CPU times: user 356 µs, sys: 0 ns, total: 356 µs
Wall time: 365 µs


array([[3.54262565e-01, 3.55396306e-01, 3.74293381e-01, ...,
        4.09159937e-01, 4.12724845e-01, 1.00000000e+04],
       [4.73876682e-01, 4.74090234e-01, 4.91546604e-01, ...,
        5.04272814e-01, 5.05969448e-01, 5.07060443e-01],
       [4.91069871e-01, 4.99491491e-01, 5.04809216e-01, ...,
        5.35762477e-01, 5.50845190e-01, 1.00000000e+04],
       ...,
       [3.76518875e-01, 3.93194616e-01, 3.93275729e-01, ...,
        4.02001756e-01, 4.03970985e-01, 1.00000000e+04],
       [8.61833045e-02, 1.38970976e-01, 1.43215593e-01, ...,
        2.43290125e-01, 2.47679775e-01, 2.50551390e-01],
       [2.80074201e-01, 3.45120891e-01, 3.49436687e-01, ...,
        4.20504208e-01, 4.21100043e-01, 1.00000000e+04]])

In [89]:
index_df

0  new_arr_idx     value  old_idx
0       0            0  0.381125      433
1       0            1  0.374293      803
2       0            2  0.380547      932
3       0            3  0.409160     1256
4       0            4  0.355396     1427
...   ...          ...       ...      ...
1667  175            4  0.421100     1777
1668  175            5  0.420139     1854
1669  175            6  0.420504     2253
1670  175            7  0.280074     2569
1671  175            8  0.373626     2926

[1672 rows x 4 columns]

In [97]:
np.arange(1, 177, 1).reshape(-1, 1).shape

(176, 1)

In [105]:
ann_relative_2.shape

(176, 10)

In [110]:
%time count_arr = np.arange(176*10).reshape(176, 10)#.shape

CPU times: user 154 µs, sys: 0 ns, total: 154 µs
Wall time: 158 µs


In [113]:
ann_relative_2

array([[7, 4, 1, ..., 3, 8, 9],
       [0, 4, 6, ..., 9, 5, 3],
       [1, 0, 4, ..., 8, 3, 9],
       ...,
       [7, 3, 2, ..., 1, 8, 9],
       [9, 2, 0, ..., 8, 5, 3],
       [7, 2, 1, ..., 6, 4, 9]])

In [114]:
# make values in the array position-dependend
%time ann_relative_2 + count_arr * count_arr

CPU times: user 163 µs, sys: 7 µs, total: 170 µs
Wall time: 174 µs


array([[      7,       5,       5, ...,      52,      72,      90],
       [    100,     125,     150, ...,     298,     329,     364],
       [    401,     441,     488, ...,     737,     787,     850],
       ...,
       [2992907, 2996364, 2999826, ..., 3017170, 3020652, 3024130],
       [3027609, 3031083, 3034564, ..., 3052017, 3055509, 3059004],
       [3062507, 3066003, 3069505, ..., 3087055, 3090568, 3094090]])

In [119]:
ann_relative_2.shape

(176, 10)

In [116]:
index_df[1] = index_df[0] + 1
index_df['pos_mapping'] = index_df.index*index_df.index

In [118]:
index_df['pos_mapping'].max()

2792241

In [120]:
176*10

1760

In [103]:
index_df[1]

0  new_arr_idx     value  old_idx    1  pos_mapping
0       0            0  0.381125      433    1            0
1       0            1  0.374293      803    1            1
2       0            2  0.380547      932    1            2
3       0            3  0.409160     1256    1            3
4       0            4  0.355396     1427    1            4
...   ...          ...       ...      ...  ...          ...
1667  175            4  0.421100     1777  176          704
1668  175            5  0.420139     1854  176          880
1669  175            6  0.420504     2253  176         1056
1670  175            7  0.280074     2569  176         1232
1671  175            8  0.373626     2926  176         1408

[1672 rows x 6 columns]

In [99]:
ann_relative_2

array([[7, 4, 1, ..., 3, 8, 9],
       [0, 4, 6, ..., 9, 5, 3],
       [1, 0, 4, ..., 8, 3, 9],
       ...,
       [7, 3, 2, ..., 1, 8, 9],
       [9, 2, 0, ..., 8, 5, 3],
       [7, 2, 1, ..., 6, 4, 9]])

In [93]:
ann_relative_2.shape

(176, 10)

In [86]:
pure_arr

array([[0.58516339, 0.57479123, 0.59408487, ..., 0.83530635, 0.72327197,
        0.59838322],
       [0.72275381, 0.60222068, 0.58674307, ..., 0.77942052, 0.62807737,
        0.57211713],
       [0.69655005, 0.68323838, 0.72931336, ..., 0.81818156, 0.72211767,
        0.68948835],
       ...,
       [0.60102186, 0.45755973, 0.54146313, ..., 0.74456989, 0.62467989,
        0.54837613],
       [0.48865181, 0.41438067, 0.44838671, ..., 0.61604586, 0.56608649,
        0.45800737],
       [0.56945267, 0.47021571, 0.58339588, ..., 0.68409612, 0.53731712,
        0.50887008]])

In [85]:
bucket_obj_indexes

Int64Index([   63,   111,   124,   134,   266,   317,   341,   357,   394,
              424,
            ...
            99610, 99656, 99687, 99689, 99699, 99700, 99701, 99716, 99722,
            99945],
           dtype='int64', length=3095)

In [84]:
np.where(pure_arr == dists_relative)

/mnt/storage-brno11-elixir/home/tslaninakova/dynamic-lmi/dynamic-lmi-env/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


(array([], dtype=int64),)

In [78]:
g = index_df.groupby(0) #.sort_values('value').head(3)

In [67]:
pure_arr.shape

(176, 3095)

In [68]:
sample_arr.shape

(176, 10)

In [63]:
sample_arr_mapping[index_df[0].values, index_df['new_arr_idx'].values]

array([-1., -1., -1., ..., -1., -1., -1.])

In [64]:
%time sample_arr_mapping[index_df[0].values, index_df['new_arr_idx'].values] = target_dists[1]

CPU times: user 221 µs, sys: 5 µs, total: 226 µs
Wall time: 230 µs


In [77]:
sample_arr_sorted = np.sort(sample_arr, kind='quicksort')[
    :, :10
]

In [ ]:
sample_arr_mapping

In [78]:
sample_arr_sorted

array([[1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [4.91069871e-01, 4.99491491e-01, 5.04809216e-01, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       ...,
       [1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [8.61833045e-02, 1.38970976e-01, 1.43215593e-01, ...,
        2.43290125e-01, 2.47679775e-01, 2.50551390e-01],
       [2.80074201e-01, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04]])

In [66]:
ann_relative_2

array([[  0, 136, 137, ..., 142, 143, 144],
       [  0, 136, 137, ..., 142, 143, 144],
       [  1,   0,   2, ..., 140, 141, 142],
       ...,
       [  0, 136, 137, ..., 142, 143, 144],
       [ 15,   3,   1, ...,  14,   7,   4],
       [  0, 136, 137, ..., 142, 143, 144]])

In [71]:
sample_arr_mapping

array([[-1.000e+00, -1.000e+00, -1.000e+00, ..., -1.000e+00, -1.000e+00,
        -1.000e+00],
       [-1.000e+00, -1.000e+00, -1.000e+00, ..., -1.000e+00, -1.000e+00,
        -1.000e+00],
       [ 1.900e+02,  7.550e+02,  1.872e+03, ..., -1.000e+00, -1.000e+00,
        -1.000e+00],
       ...,
       [-1.000e+00, -1.000e+00, -1.000e+00, ..., -1.000e+00, -1.000e+00,
        -1.000e+00],
       [ 3.590e+02,  4.720e+02,  5.040e+02, ..., -1.000e+00, -1.000e+00,
        -1.000e+00],
       [ 2.569e+03, -1.000e+00, -1.000e+00, ..., -1.000e+00, -1.000e+00,
        -1.000e+00]])

In [68]:
ann_relative_2.shape

(176, 10)

In [70]:
sample_arr_mapping.shape

(176, 214)

In [69]:
sample_arr_mapping[ann_relative_2]

IndexError: index 181 is out of bounds for axis 0 with size 176

In [46]:
sample_arr[2, 0]

0.4994914911364663

In [54]:
index_df

0  new_arr_idx     value  old_idx
0       2            0  0.499491      190
1       2            1  0.491070      755
2       2            2  0.504809     1872
3       2            3  0.504918     2899
4       3            0  0.219707      118
...   ...          ...       ...      ...
2374  174           14  0.243290     2526
2375  174           15  0.086183     2535
2376  174           16  0.265490     2538
2377  174           17  0.293687     2995
2378  175            0  0.280074     2569

[2379 rows x 4 columns]

In [121]:
pure_arr.shape

(176, 3095)

In [124]:
result = pure_arr

In [125]:
thresh_consistent = np.repeat(threshold[cat_idxs, np.newaxis], result.shape[1], 1)
thresh_consistent

NameError: name 'threshold' is not defined

In [123]:
sample_arr

array([[3.81125490e-01, 3.74293381e-01, 3.80546576e-01, ...,
        3.54262565e-01, 4.12724845e-01, 1.00000000e+04],
       [4.73876682e-01, 4.96774658e-01, 5.00576416e-01, ...,
        5.04241098e-01, 4.96301041e-01, 5.04272814e-01],
       [4.99491491e-01, 4.91069871e-01, 5.22439371e-01, ...,
        5.04918345e-01, 5.35762477e-01, 1.00000000e+04],
       ...,
       [3.98160039e-01, 4.02001756e-01, 3.93275729e-01, ...,
        3.76518875e-01, 4.03970985e-01, 1.00000000e+04],
       [1.43215593e-01, 2.17929883e-01, 1.38970976e-01, ...,
        2.16701151e-01, 2.43290125e-01, 8.61833045e-02],
       [3.97648318e-01, 3.49436687e-01, 3.45120891e-01, ...,
        2.80074201e-01, 3.73626027e-01, 1.00000000e+04]])

In [236]:
sample_arr.shape

(176, 214)

In [56]:
ann_relative_2

array([[  0, 136, 137, ..., 142, 143, 144],
       [  0, 136, 137, ..., 142, 143, 144],
       [  1,   0,   2, ..., 140, 141, 142],
       ...,
       [  0, 136, 137, ..., 142, 143, 144],
       [ 15,   3,   1, ...,  14,   7,   4],
       [  0, 136, 137, ..., 142, 143, 144]])

In [ ]:
ann_relative_2

In [242]:
dists_res = np.take_along_axis(sample_arr, ann_relative_2, axis=1)

In [243]:
dists_res

array([[1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [4.91069871e-01, 4.99491491e-01, 5.04809216e-01, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       ...,
       [1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [8.61833045e-02, 1.38970976e-01, 1.43215593e-01, ...,
        2.43290125e-01, 2.47679775e-01, 2.50551390e-01],
       [2.80074201e-01, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04]])

In [241]:
dists[cat_idxs]

array([[0.16662204, 0.26132104, 0.28283674, ..., 0.3248234 , 0.32667616,
        0.3311572 ],
       [0.4429067 , 0.4474052 , 0.45352405, ..., 0.4677359 , 0.46902606,
        0.46920323],
       [0.48189315, 0.4886164 , 0.48993993, ..., 0.5114319 , 0.51531136,
        0.5171687 ],
       ...,
       [0.30622727, 0.33433402, 0.33730066, ..., 0.361187  , 0.36834347,
        0.3712152 ],
       [0.08808586, 0.20122772, 0.21688594, ..., 0.2642632 , 0.2695809 ,
        0.3098314 ],
       [0.2283353 , 0.25617176, 0.27532452, ..., 0.29867372, 0.30868042,
        0.3158128 ]], dtype=float32)

In [244]:
dists[cat_idxs]

array([[0.16662204, 0.26132104, 0.28283674, ..., 0.3248234 , 0.32667616,
        0.3311572 ],
       [0.4429067 , 0.4474052 , 0.45352405, ..., 0.4677359 , 0.46902606,
        0.46920323],
       [0.48189315, 0.4886164 , 0.48993993, ..., 0.5114319 , 0.51531136,
        0.5171687 ],
       ...,
       [0.30622727, 0.33433402, 0.33730066, ..., 0.361187  , 0.36834347,
        0.3712152 ],
       [0.08808586, 0.20122772, 0.21688594, ..., 0.2642632 , 0.2695809 ,
        0.3098314 ],
       [0.2283353 , 0.25617176, 0.27532452, ..., 0.29867372, 0.30868042,
        0.3158128 ]], dtype=float32)

In [246]:
dists_res

array([[1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [4.91069871e-01, 4.99491491e-01, 5.04809216e-01, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       ...,
       [1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [8.61833045e-02, 1.38970976e-01, 1.43215593e-01, ...,
        2.43290125e-01, 2.47679775e-01, 2.50551390e-01],
       [2.80074201e-01, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04]])

In [235]:
sample_arr

array([[1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [4.99491491e-01, 4.91069871e-01, 5.04809216e-01, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       ...,
       [1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [3.05168964e-01, 1.43215593e-01, 2.17929883e-01, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [2.80074201e-01, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04]])

In [253]:
dists_final = np.hstack((dists[cat_idxs], dists_res))
dists_final.shape

(176, 20)

In [254]:
dists_final

array([[1.66622043e-01, 2.61321038e-01, 2.82836735e-01, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [4.42906708e-01, 4.47405189e-01, 4.53524053e-01, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [4.81893152e-01, 4.88616407e-01, 4.89939928e-01, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       ...,
       [3.06227267e-01, 3.34334016e-01, 3.37300658e-01, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [8.80858600e-02, 2.01227725e-01, 2.16885939e-01, ...,
        2.43290125e-01, 2.47679775e-01, 2.50551390e-01],
       [2.28335306e-01, 2.56171763e-01, 2.75324523e-01, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04]])

In [255]:
dists_final.argsort(kind='stable', axis=1)[:, :k]

array([[ 0,  1,  2, ...,  7,  8,  9],
       [ 0,  1,  2, ...,  7,  8,  9],
       [ 0,  1,  2, ...,  5, 12, 13],
       ...,
       [ 0,  1,  2, ...,  7,  8,  9],
       [10,  0, 11, ..., 15,  2, 16],
       [ 0,  1,  2, ...,  6,  7,  8]])

In [ ]:
    anns_final = np.hstack((anns_final, anns))
    dists_final = np.hstack((dists_final, dists))
    # gets the sorted indices of the stacked dists
    idx_sorted = dists_final.argsort(kind='stable', axis=1)[:, :k]

In [222]:
index_df.values.max()

213

In [212]:
target_dists[0]

array([  2,   2,   2, ..., 174, 174, 175])

In [226]:
index_df.values[:, 0].max(), index_df.values[:, 1].max()

(175, 213)

In [228]:
sample_arr.shape

(176, 214)

In [203]:
%time target_dists[1][target_dists[0] == 2]

CPU times: user 133 µs, sys: 9 µs, total: 142 µs
Wall time: 146 µs


array([ 190,  755, 1872, 2899])

In [186]:
# return_index=True, return_inverse=True
np.unique(np.argwhere(pure_arr < res)[:, 0], return_inverse=True)

(array([  2,   3,   4,   7,   8,   9,  10,  11,  13,  14,  16,  18,  19,
         20,  21,  23,  24,  25,  26,  27,  28,  29,  31,  32,  33,  35,
         37,  38,  40,  41,  43,  45,  46,  47,  48,  49,  50,  51,  52,
         53,  55,  56,  57,  58,  59,  60,  61,  63,  64,  65,  66,  67,
         68,  69,  70,  71,  72,  74,  75,  77,  78,  80,  81,  83,  84,
         85,  86,  88,  89,  91,  92,  93,  94,  95,  97,  98,  99, 100,
        101, 102, 103, 104, 105, 106, 109, 110, 114, 115, 117, 118, 119,
        120, 121, 122, 123, 124, 125, 127, 128, 130, 131, 132, 133, 135,
        136, 137, 138, 139, 140, 141, 142, 145, 147, 148, 149, 151, 153,
        154, 155, 156, 159, 160, 161, 162, 163, 165, 168, 169, 172, 174,
        175]),
 array([  0,   0,   0, ..., 129, 129, 130]))

In [183]:
%time max_arr = np.unique(np.argwhere(pure_arr < res)[:, 0], return_counts=True)[1].max()

CPU times: user 2.43 ms, sys: 0 ns, total: 2.43 ms
Wall time: 2.44 ms


In [ ]:
sample_arr

In [181]:
%time res2_w = np.where(pure_arr < res)

CPU times: user 2.32 ms, sys: 0 ns, total: 2.32 ms
Wall time: 6.9 ms


In [180]:
%time res2 = np.argwhere(pure_arr < res)

CPU times: user 3.99 ms, sys: 0 ns, total: 3.99 ms
Wall time: 4 ms


In [182]:
res2_w

(array([  2,   2,   2, ..., 174, 174, 175]),
 array([ 190,  755, 1872, ..., 2538, 2995, 2569]))

In [145]:
res2

array([[   2,  190],
       [   2,  755],
       [   2, 1872],
       ...,
       [ 174, 2538],
       [ 174, 2995],
       [ 175, 2569]])

In [ ]:
res2

In [179]:
res2[:, 1]

array([ 190,  755, 1872, ..., 2538, 2995, 2569])

In [147]:
sample_arr[2, 0] = pure_arr[res2]

In [146]:
pure_arr[2, 190]

0.4994914911364663

In [149]:
pure_arr[res2].shape

IndexError: index 190 is out of bounds for axis 0 with size 176

In [148]:
sample_arr

array([[1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [4.99491491e-01, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       ...,
       [1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04],
       [1.00000000e+04, 1.00000000e+04, 1.00000000e+04, ...,
        1.00000000e+04, 1.00000000e+04, 1.00000000e+04]])

In [137]:
res2[res2 == 2]

array([2, 2, 2, 2, 2, 2])

In [138]:
sample_arr[res2[:, 0]] = res2[:, 1]

ValueError: shape mismatch: value array of shape (2379,) could not be broadcast to indexing result of shape (2379,214)

In [ ]:
sample_arr

In [ ]:
dists = np.zeros((queries_search.shape[0], k), dtype=np.float32)

In [126]:
np.argwhere(pure_arr < res)

array([[   2,  190],
       [   2,  755],
       [   2, 1872],
       ...,
       [ 174, 2538],
       [ 174, 2995],
       [ 175, 2569]])

In [128]:
pure_arr[2, 190]

0.4994914911364663

In [123]:
np.where(pure_arr < res)[0][:100]

array([ 2,  2,  2,  2,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  7,  7,  8,  8,  8,  9,  9,  9,  9,  9,  9, 10,
       10, 10, 11, 11, 11, 11, 11, 13, 13, 13, 13, 13, 13, 13, 14, 14, 14,
       14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
       14, 14, 14, 14, 14, 14, 14, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
       16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16])

In [124]:
np.where(pure_arr < res)[1][:100]

array([ 190,  755, 1872, 2899,  118,  386,  659,  775, 1064, 1070, 1582,
       2979,   36,  127,  178,  363,  502,  603,  850,  942, 1095, 2433,
       1142, 1237,  724,  752, 2683,   71,  498, 1967, 2055, 2505, 2930,
        276, 1820, 2939,  567,  627, 1121, 2369, 2930,  497, 1327, 1354,
       1537, 1735, 2349, 2705,   86,  222,  258,  356,  450,  487,  511,
        578,  667,  675,  969,  977, 1326, 1490, 1546, 1660, 2075, 2081,
       2204, 2409, 2492, 2556, 2907, 2921, 2939, 2964, 3020,   20,   59,
         63,   68,   99,  101,  139,  162,  209,  229,  304,  305,  320,
        337,  341,  374,  387,  410,  452,  456,  478,  509,  520,  525,
        536])

In [125]:
pure_arr[np.where(pure_arr < res)[0][:100], np.where(pure_arr < res)[1][:100]]

array([0.49949149, 0.49106987, 0.50480922, 0.50491835, 0.21970675,
       0.21747319, 0.20134505, 0.18773172, 0.22785204, 0.20411416,
       0.18883318, 0.22479822, 0.2812132 , 0.4159223 , 0.26609447,
       0.2619391 , 0.41588517, 0.40184208, 0.39325575, 0.24603255,
       0.35324137, 0.41466428, 0.36104663, 0.43005669, 0.33777408,
       0.31274958, 0.32374122, 0.39482597, 0.39811506, 0.39745085,
       0.39433688, 0.39809865, 0.38307477, 0.33959513, 0.34356986,
       0.30563943, 0.41887541, 0.40099864, 0.42117212, 0.40196987,
       0.40889696, 0.33866255, 0.32742303, 0.34803717, 0.31747813,
       0.34207842, 0.34846552, 0.34598291, 0.44701626, 0.43784671,
       0.36496563, 0.43637098, 0.48160728, 0.38970633, 0.48853607,
       0.49631695, 0.46954897, 0.49961672, 0.39478519, 0.43095072,
       0.5074329 , 0.35632667, 0.38003825, 0.4954067 , 0.41376934,
       0.47545652, 0.44329446, 0.40261632, 0.46516595, 0.34723944,
       0.44903738, 0.50536929, 0.42128971, 0.48607873, 0.47917

In [122]:
pure_arr[np.where(pure_arr < res)].shape

(2379,)

In [105]:
(np.array(dists.max(axis=1)[cat_idxs],)*5).T.shape

(176,)

In [99]:
np.tile(dists.max(axis=1)[cat_idxs], (176, 2)).shape

(176, 352)

In [90]:
pure_arr[1][pure_arr[1] < np.hstack(dists.max(axis=1)[cat_idxs][1], )

array([], dtype=float64)

In [85]:
np.where(pure_arr < 0.79674435)[0].shape

(536398,)

In [ ]:
pure_arr[np.where(pure_arr < 0.79674435)]

In [83]:
pure_arr[np.where(pure_arr < 0.79674435)].reshape(pure_arr.shape[0], -1)

ValueError: cannot reshape array of size 536398 into shape (176,newaxis)

In [39]:
pure_arr.shape

(176, 3095)

In [50]:
pure_arr[:2]

array([[0.58516339, 0.57479123, 0.59408487, ..., 0.83530635, 0.72327197,
        0.59838322],
       [0.72275381, 0.60222068, 0.58674307, ..., 0.77942052, 0.62807737,
        0.57211713]])

In [67]:
d = dists.max(axis=1)

In [68]:
d[d < 10_000].max()

0.79674435

In [66]:
np.sort(dists.max(axis=1))

array([-4.440892e-16, -4.440892e-16, -4.440892e-16, ...,  1.000000e+04,
        1.000000e+04,  1.000000e+04], dtype=float32)

In [51]:
dists.max(axis=1)[cat_idxs[:2]]

array([0.3311572 , 0.46920323], dtype=float32)

In [57]:
pure_arr[:2][0]

array([0.58516339, 0.57479123, 0.59408487, ..., 0.83530635, 0.72327197,
       0.59838322])

In [73]:
np.argwhere(pure_arr < d[d < 10_000].max())

array([[   0,    0],
       [   0,    1],
       [   0,    2],
       ...,
       [ 175, 3092],
       [ 175, 3093],
       [ 175, 3094]])

In [72]:
pure_arr[np.argwhere(pure_arr < d[d < 10_000].max())].shape

IndexError: index 176 is out of bounds for axis 0 with size 176

In [71]:
pure_arr.shape

(176, 3095)

In [53]:
mask = pure_arr[:2] > dists.max(axis=1)[cat_idxs[:2]]

ValueError: operands could not be broadcast together with shapes (2,3095) (2,) 

In [49]:
pure_arr[:2] < dists.max(axis=1)[cat_idxs[:2]]

ValueError: operands could not be broadcast together with shapes (2,3095) (2,) 

In [45]:
pure_arr[pure_arr < dists.max(axis=1)[cat_idxs]].shape

ValueError: operands could not be broadcast together with shapes (176,3095) (176,) 

In [ ]:
dists, anns, t_all, t_pairwise = self.search_single(
    data_navigation,
    data_search,
    queries_search,
    pred_proba_categories[:, bucket]
)